<?php

declare(strict_types=1);

namespace SanderMuller\BoostCore\Sync;

/**
 * Maintains a managed block inside `.gitignore` listing the paths boost
 * generates. Lines outside the sentinels are preserved verbatim.
 *
 * Behavior:
 * - block missing + patterns non-empty → append block
 * - block exists + patterns non-empty → rebuild block in place
 * - block exists + patterns empty     → strip block
 * - block missing + patterns empty    → no change
 *
 * Opt-out is at the caller layer (e.g., a `BoostConfig` flag) — this class
 * always performs the requested operation.
 */
final class GitignoreManager
{
    public const START = '# >>> boost (managed) >>>';

    public const END = '# <<< boost (managed) <<<';

    private const NOTE = '# Generated by boost-core. Edit .ai/ instead.';

    /**
     * Returns the new contents, or null if no change is needed relative to `$existing`.
     *
     * @param  list<string>  $patterns
     */
    public function render(?string $existing, array $patterns): ?string
    {
        $patterns = $this->normalize($patterns);
        $existing ??= '';

        [$before, $hasBlock, $after] = $this->split($existing);

        if (! $hasBlock && $patterns === []) {
            return null;
        }

        if (! $hasBlock) {
            return $this->appendBlock($existing, $patterns);
        }

        if ($patterns === []) {
            $stripped = $this->stripBlock($before, $after);

            return $stripped === $existing ? null : $stripped;
        }

        $rebuilt = $this->joinAround($before, $this->buildBlock($patterns), $after);

        return $rebuilt === $existing ? null : $rebuilt;
    }

    /**
     * @return array{0: string, 1: bool, 2: string}
     */
    private function split(string $contents): array
    {
        $startPos = strpos($contents, self::START);
        if ($startPos === false) {
            return [$contents, false, ''];
        }

        $endPos = strpos($contents, self::END, $startPos);
        if ($endPos === false) {
            return [$contents, false, ''];
        }

        $endLineEnd = strpos($contents, "\n", $endPos);
        $after = $endLineEnd === false ? '' : substr($contents, $endLineEnd + 1);

        return [substr($contents, 0, $startPos), true, $after];
    }

    /**
     * @param  list<string>  $patterns
     * @return list<string>
     */
    private function normalize(array $patterns): array
    {
        $seen = [];
        foreach ($patterns as $pattern) {
            $trimmed = trim($pattern);
            if ($trimmed === '') {
                continue;
            }

            $seen[$trimmed] = true;
        }

        $unique = array_keys($seen);
        sort($unique);

        return $unique;
    }

    /**
     * @param  list<string>  $patterns
     */
    private function appendBlock(string $existing, array $patterns): string
    {
        $separator = $existing === '' ? '' : (str_ends_with($existing, "\n") ? '' : "\n");

        return $existing . $separator . $this->buildBlock($patterns);
    }

    /**
     * @param  list<string>  $patterns
     */
    private function buildBlock(array $patterns): string
    {
        $lines = [self::START, self::NOTE];
        foreach ($patterns as $pattern) {
            $lines[] = $pattern;
        }

        $lines[] = self::END;

        return implode("\n", $lines) . "\n";
    }

    private function joinAround(string $before, string $block, string $after): string
    {
        if ($before !== '' && ! str_ends_with($before, "\n")) {
            $before .= "\n";
        }

        return $before . $block . $after;
    }

    private function stripBlock(string $before, string $after): string
    {
        $before = rtrim($before, "\n");
        if ($before === '' && $after === '') {
            return '';
        }

        if ($after === '') {
            return $before . "\n";
        }

        return ($before === '' ? '' : $before . "\n") . $after;
    }
}
