<?php declare(strict_types=1);

namespace SanderMuller\BoostCore\Sync;

use SanderMuller\BoostCore\Conventions\ManagedRegion;

/**
 * Maintains a managed block inside `.gitignore` listing the paths boost
 * generates. Lines outside the sentinels are preserved verbatim.
 *
 * Behavior:
 * - block missing + patterns non-empty → append block
 * - block exists + patterns non-empty → rebuild block in place
 * - block exists + patterns empty     → strip block
 * - block missing + patterns empty    → no change
 *
 * Opt-out is at the caller layer (e.g., a `BoostConfig` flag) — this class
 * always performs the requested operation.
 *
 * The marker-bounded round-trip logic delegates to {@see ManagedRegion}.
 * `.gitignore`-specific concerns (pattern normalization, sort, dedup) stay here.
 *
 * @internal
 */
final readonly class GitignoreManager
{
    public const START = '# >>> boost (managed) >>>';

    public const END = '# <<< boost (managed) <<<';

    private const NOTE = '# Generated by boost-core. Edit .ai/ instead.';

    private ManagedRegion $region;

    public function __construct()
    {
        $this->region = new ManagedRegion(
            start: self::START,
            end: self::END,
            note: self::NOTE,
        );
    }

    /**
     * Returns the new contents, or null if no change is needed relative to `$existing`.
     *
     * @param  list<string>  $patterns
     */
    public function render(?string $existing, array $patterns): ?string
    {
        $normalized = $this->normalize($patterns);

        return $this->region->render($existing, implode("\n", $normalized));
    }

    /**
     * @param  list<string>  $patterns
     * @return list<string>
     */
    private function normalize(array $patterns): array
    {
        $seen = [];
        foreach ($patterns as $pattern) {
            $trimmed = trim($pattern);
            if ($trimmed === '') {
                continue;
            }

            $seen[$trimmed] = true;
        }

        $unique = array_keys($seen);
        sort($unique);

        return $unique;
    }
}
