<?php declare(strict_types=1);

namespace SanderMuller\BoostCore\Config;

/**
 * Generates the starter `boost.php` for a project that doesn't have one.
 *
 * Extracted from `boost install` so every command that can bootstrap a project
 * (`boost install`, `boost remote`) writes the SAME starter — a second,
 * drifting copy of the template is the bug class this class exists to prevent.
 *
 * @internal
 */
final readonly class ConfigScaffolder
{
    /**
     * Where a fresh scaffold lands: edit the existing config wherever it lives;
     * otherwise root by default, or `.config/boost.php` when `--config-dir` is set.
     * Never picks a second location when one already exists.
     */
    public static function target(BoostConfigPath $resolved, bool $useConfigDir, string $projectRoot): string
    {
        if ($resolved->exists) {
            return $resolved->path;
        }

        $projectRoot = rtrim($projectRoot, '/');

        return $useConfigDir
            ? $projectRoot . '/' . BoostConfigPath::CONFIG_DIR
            : $projectRoot . '/' . BoostConfigPath::ROOT;
    }

    /**
     * Write the starter template to `$configPath`, creating the parent
     * directory when needed.
     *
     * @throws BoostConfigWriteException when the directory or file cannot be written
     */
    public static function scaffold(string $configPath): void
    {
        $dir = dirname($configPath);
        if (! is_dir($dir) && ! @mkdir($dir, 0o755, recursive: true) && ! is_dir($dir)) {
            throw new BoostConfigWriteException($configPath, sprintf('failed to create directory %s.', $dir));
        }

        if (file_put_contents($configPath, self::starterContents()) === false) {
            throw new BoostConfigWriteException($configPath, 'failed to write the starter boost.php.');
        }
    }

    public static function starterContents(): string
    {
        return <<<'PHP'
            <?php declare(strict_types=1);

            use SanderMuller\BoostCore\Config\BoostConfig;
            use SanderMuller\BoostCore\Enums\Agent;
            use SanderMuller\BoostCore\Enums\Tag;
            use SanderMuller\BoostCore\Skills\Remote\RemoteSkillSource;

            /**
             * boost-core configuration.
             *
             * Generated by `vendor/bin/boost install`. Re-run that command to update
             * agents/vendors interactively, or hand-edit this file. After changes
             * run `vendor/bin/boost sync`.
             *
             * Docs: https://github.com/sandermuller/boost-core
             */
            return BoostConfig::configure()
                // Which AI agents to publish skills/guidelines to. Add Agent enum cases.
                // Example: Agent::CLAUDE_CODE, Agent::CURSOR, Agent::COPILOT
                ->withAgents([])

                // Vendor packages allowed to publish skills/guidelines into your project.
                // Each entry is a Composer package name. Add via `vendor/bin/boost scan` or hand-edit.
                ->withAllowedVendors([])

                // Skill sources fetched from GitHub rather than Composer. Add
                // entries interactively with `vendor/bin/boost remote <owner>/<repo>`.
                ->withRemoteSkills([])

                // Optionally disable specific FileEmitter implementations by FQCN.
                // ->withDisabledEmitters([SomeFqcn::class])

                // Skill tags: a vendor skill ships only when every tag in its
                // `metadata.boost-tags` is declared here. Unset = receive every
                // (untagged) skill. Accepts Tag enum cases or raw strings.
                // ->withTags([Tag::Php, Tag::Laravel])

                // Exclude specific vendor skills regardless of tags.
                // Each entry is a `vendor/package:skill-name` string.
                // ->withExcludedSkills(['acme/some-pack:unwanted-skill'])

                // Source paths default to the project root's .ai/skills and
                // .ai/guidelines. Override with an ABSOLUTE path only if your
                // sources live elsewhere. Avoid __DIR__-relative paths — they
                // break if this file moves (e.g. into .config/).
                // ->withSkillsPath('/absolute/path/to/skills')
                // ->withGuidelinesPath('/absolute/path/to/guidelines')
            ;

            PHP;
    }
}
